### ISSUE TITLE
It failed to handle appointment of doctor at our clinic

### ISSUE THREAD

**Issue by mujtaba-io** [HasaanAhmad/Appointment-Managment-System#1]
We tried your system at our clinic and unfortunately, it assigned the same doctor to many patients at the same time. The doctor resigned after being burdened by this.

**Comment by HasaanAhmad** [comment]
Ohh, God! That's Sad to hear. I forwarded your query to the development team. They are working on the issue. In addition to it, we can offer you a doctor to work at your clinic for a while.
